name: Run Tests

on:
  push:
    branches:
      - main # Default branch

jobs:
  test:
    name: Runs tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8,11,17,21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: Prepare Leiningen
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          lein: latest

      - name: Run tests
        run: lein test
